// Generated by CoffeeScript 1.6.1
(function() {
  var chooseFileText, initializeFileInput;

  chooseFileText = "Choose a file";

  $(document).ready(function() {
    return $('input[type="file"]').each(initializeFileInput);
  });

  initializeFileInput = function() {
    var customFileInputWrapper, invisibleWrapper, label, realFileInput;
    realFileInput = $(this);
    label = $('<div class="file-input-button">' + chooseFileText + '</div>');
    invisibleWrapper = $('<div></div>').css({
      height: 0,
      width: 0,
      'overflow': 'hidden'
    });
    customFileInputWrapper = $('<div class="custom-file-input"></div>');
    realFileInput.wrap(customFileInputWrapper).after(label).wrap(invisibleWrapper);
    realFileInput.change(function() {
      var fileName, fileNameList;
      fileNameList = $(this).parent().parent().find('.file-name');
      if (fileNameList.length > 0) {
        return fileNameList.first().text($(this).val());
      } else {
        fileName = $('<div class="file-name">' + $(this).val() + '</div>');
        return label.after(fileName);
      }
    });
    return label.click(function() {
      return label.prev().children().first().click();
    });
  };

}).call(this);
